services:
  interschool-builder:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.services.builder.loadbalancer.server.port=5000"
      - "traefik.http.routers.builder.rule=Host(`builder.rxq.ch`)"
      - "traefik.http.routers.builder.entrypoints=web"
      - "traefik.http.routers.builder.middlewares=https_redirect"
      - "traefik.http.routers.builder_secured.rule=Host(`builder.rxq.ch`)"
      - "traefik.http.routers.builder_secured.entrypoints=websecure"
      - "traefik.http.routers.builder_secured.tls=true"
      - "traefik.http.routers.builder_secured.tls.certresolver=myresolver"
    networks:
      - web
  mail:
    image: axllent/mailpit
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.mail.rule=Host(`mail.rxq.ch`)"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.routers.mail.middlewares=https_redirect"
      - "traefik.http.routers.mail_secured.rule=Host(`mail.rxq.ch`)"
      - "traefik.http.routers.mail_secured.entrypoints=websecure"
      - "traefik.http.routers.mail_secured.tls=true"
      - "traefik.http.routers.mail_secured.tls.certresolver=myresolver"
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=True
      - MP_SMTP_AUTH_ALLOW_INSECURE=True
    networks:
      - web      
networks:
  web:
    external: true
